language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - "pip install -U pip"
install:
  - "pip install -U six"
  - "pip install -U pyplink"
  - "pip install -U coveralls"
script: "python test_beelinetools.py"
after_success: "coveralls"
